version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: bd
      MYSQL_ROOT_PASSWORD: password # Only this variable is needed for root user
    ports:
      - '3316:3306' # Host port:Container port
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - springboot-mysql

  app:
    build: 
      context: emp_backend
    image: spring-app
    container_name: springboot
    restart: always
    ports:
      - '8090:8080' # Host port:Container port
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/bd
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - mysql
    networks:
      - springboot-mysql
    volumes:
      - app-data:/app/uploads
      - release-notes:/app/release_notes:rw  # Monte le fichier release dans le conteneur

  frontend:
    build: 
      context: employee frontend final
    image: angular-app
    container_name: angular-container
    restart: always
    ports:
      - '4200:80' # Nginx sert l'application sur le port 80
    depends_on:
      - app
    networks:
      - springboot-mysql

volumes:
  mysql-data:
  app-data:

networks:
  springboot-mysql:
    driver: bridge